name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run
      run: |
        mkdir megafield
        cd megafield
        ../target/release/mandelbrot

    - uses: actions/upload-artifact@v1
      with:
        name: megafield
        path: megafield/